name: Test Native Installation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  native_install:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        release: ["lilac"]
    env:
      OPENEDX_RELEASE: open-release/${{ matrix.release }}.master

    steps:
      - name: Remove MySQL
        run: |
          sudo service mysql stop
          sudo apt-get remove --purge mysql-server mysql-client mysql-common -y
          sudo apt-get autoremove
          sudo apt-get autoclean
          sudo rm -rf /var/lib/mysql
      - name: Remove MongoDB
        run: |
          sudo service mongod stop
          sudo apt-get purge mongodb-org*
          sudo rm -r /var/log/mongodb
          sudo rm -r /var/lib/mongodb
      - name: Clear Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          df -h
      - name: Ansible Bootstrap
        run: wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/ansible-bootstrap.sh -O - | sudo -E bash
      - name: Generate passwords
        run: |
          wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/generate-passwords.sh -O - | bash
          ls -l
      - name: Create config.yml
        run: |
          echo -e "EDXAPP_LMS_BASE: '$(curl ipinfo.io/ip)'\nEDXAPP_CMS_BASE: '$(curl ipinfo.io/ip):18010'\nSANDBOX_ENABLE_DISCOVERY: true" > config.yml
          ls -l
      - name: Native Install
        run: wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/native.sh -O - | bash
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
          payload: '{"job":"https://github.com/${{ github.repository}}/actions/workflows/run-native-install.yml","status":"${{ job.status }}","release":"${{ env.OPENEDX_RELEASE }}"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
      - name: Disk Space
        run: df -h
        if: always()
